apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: neo-savant-2
  namespace: neo-savant-2
  labels:
    app.kubernetes.io/name: neo-savant-2
spec:
  domains:
    - ide.zilliqa.com
