apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: neo-savant-2
  namespace: neo-savant-2
  labels:
    app.kubernetes.io/name: neo-savant-2
spec:
  timeoutSec: 120
  healthCheck:
    requestPath: /
